// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_service.proto

package tech.hry.logclient.grpc;

/**
 * Protobuf enum {@code LogLevel}
 */
public enum LogLevel
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>TRACE = 0;</code>
   */
  TRACE(0),
  /**
   * <code>DEBUG = 1;</code>
   */
  DEBUG(1),
  /**
   * <code>INFO = 2;</code>
   */
  INFO(2),
  /**
   * <code>WARNING = 3;</code>
   */
  WARNING(3),
  /**
   * <code>ERROR = 4;</code>
   */
  ERROR(4),
  /**
   * <code>SERVICE = 5;</code>
   */
  SERVICE(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TRACE = 0;</code>
   */
  public static final int TRACE_VALUE = 0;
  /**
   * <code>DEBUG = 1;</code>
   */
  public static final int DEBUG_VALUE = 1;
  /**
   * <code>INFO = 2;</code>
   */
  public static final int INFO_VALUE = 2;
  /**
   * <code>WARNING = 3;</code>
   */
  public static final int WARNING_VALUE = 3;
  /**
   * <code>ERROR = 4;</code>
   */
  public static final int ERROR_VALUE = 4;
  /**
   * <code>SERVICE = 5;</code>
   */
  public static final int SERVICE_VALUE = 5;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LogLevel valueOf(int value) {
    return forNumber(value);
  }

  public static LogLevel forNumber(int value) {
    switch (value) {
      case 0: return TRACE;
      case 1: return DEBUG;
      case 2: return INFO;
      case 3: return WARNING;
      case 4: return ERROR;
      case 5: return SERVICE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LogLevel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LogLevel> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LogLevel>() {
          public LogLevel findValueByNumber(int number) {
            return LogLevel.forNumber(number);
          }
        };

  private final int value;

  private LogLevel(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:LogLevel)
}

