// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_service.proto

package tech.hry.logclient.grpc;

/**
 * Protobuf enum {@code LogLevel}
 */
public enum LogLevel
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TRACE = 0;</code>
   */
  TRACE(0),
  /**
   * <code>DEBUG = 1;</code>
   */
  DEBUG(1),
  /**
   * <code>INFO = 2;</code>
   */
  INFO(2),
  /**
   * <code>WARNING = 3;</code>
   */
  WARNING(3),
  /**
   * <code>ERROR = 4;</code>
   */
  ERROR(4),
  /**
   * <code>SERVICE = 5;</code>
   */
  SERVICE(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TRACE = 0;</code>
   */
  public static final int TRACE_VALUE = 0;
  /**
   * <code>DEBUG = 1;</code>
   */
  public static final int DEBUG_VALUE = 1;
  /**
   * <code>INFO = 2;</code>
   */
  public static final int INFO_VALUE = 2;
  /**
   * <code>WARNING = 3;</code>
   */
  public static final int WARNING_VALUE = 3;
  /**
   * <code>ERROR = 4;</code>
   */
  public static final int ERROR_VALUE = 4;
  /**
   * <code>SERVICE = 5;</code>
   */
  public static final int SERVICE_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LogLevel valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static LogLevel forNumber(int value) {
    switch (value) {
      case 0: return TRACE;
      case 1: return DEBUG;
      case 2: return INFO;
      case 3: return WARNING;
      case 4: return ERROR;
      case 5: return SERVICE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LogLevel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LogLevel> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LogLevel>() {
          public LogLevel findValueByNumber(int number) {
            return LogLevel.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return tech.hry.logclient.grpc.LogServiceOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final LogLevel[] VALUES = values();

  public static LogLevel valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LogLevel(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:LogLevel)
}

