// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_service.proto

package tech.hry.logclient.grpc;

public final class LogServiceOuterClass {
  private LogServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveLogRequest_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveLogRequest_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveLogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021log_service.proto\"\277\001\n\016SaveLogRequest\022\017" +
      "\n\007appName\030\001 \001(\t\022\030\n\005level\030\002 \001(\0162\t.LogLeve" +
      "l\022\r\n\005title\030\003 \001(\t\022\017\n\007message\030\004 \001(\t\022\'\n\004tag" +
      "s\030\005 \003(\0132\031.SaveLogRequest.TagsEntry\022\014\n\004ti" +
      "me\030\006 \001(\t\032+\n\tTagsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001\"\021\n\017SaveLogResponse*O\n\010LogL" +
      "evel\022\t\n\005TRACE\020\000\022\t\n\005DEBUG\020\001\022\010\n\004INFO\020\002\022\013\n\007" +
      "WARNING\020\003\022\t\n\005ERROR\020\004\022\013\n\007SERVICE\020\00528\n\nLog" +
      "Service\022*\n\005Store\022\017.SaveLogRequest\032\020.Save" +
      "LogResponseB\033\n\027tech.hry.logclient.grpcP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SaveLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SaveLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveLogRequest_descriptor,
        new java.lang.String[] { "AppName", "Level", "Title", "Message", "Tags", "Time", });
    internal_static_SaveLogRequest_TagsEntry_descriptor =
      internal_static_SaveLogRequest_descriptor.getNestedTypes().get(0);
    internal_static_SaveLogRequest_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveLogRequest_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_SaveLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SaveLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveLogResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
