// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_service.proto

package tech.hry.logclient.grpc;

public interface SaveLogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveLogResponse)
    com.google.protobuf.MessageOrBuilder {
}
