// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_service.proto

package tech.hry.logclient.grpc;

public interface SaveLogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveLogRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string appName = 1;</code>
   */
  String getAppName();
  /**
   * <code>optional string appName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAppNameBytes();

  /**
   * <code>optional .LogLevel level = 2;</code>
   */
  int getLevelValue();
  /**
   * <code>optional .LogLevel level = 2;</code>
   */
  tech.hry.logclient.grpc.LogLevel getLevel();

  /**
   * <code>optional string title = 3;</code>
   */
  String getTitle();
  /**
   * <code>optional string title = 3;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional string message = 4;</code>
   */
  String getMessage();
  /**
   * <code>optional string message = 4;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */
  boolean containsTags(
          String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */
  java.util.Map<String, String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */

  String getTagsOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */

  String getTagsOrThrow(
          String key);

  /**
   * <code>optional string time = 6;</code>
   */
  String getTime();
  /**
   * <code>optional string time = 6;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();
}
