// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_service.proto

package tech.hry.logclient.grpc;

/**
 * Protobuf type {@code SaveLogRequest}
 */
public  final class SaveLogRequest extends
    com.google.protobuf.GeneratedMessageLite<
        SaveLogRequest, SaveLogRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:SaveLogRequest)
    SaveLogRequestOrBuilder {
  private SaveLogRequest() {
    appName_ = "";
    title_ = "";
    message_ = "";
    time_ = "";
  }
  private int bitField0_;
  public static final int APPNAME_FIELD_NUMBER = 1;
  private String appName_;
  /**
   * <code>optional string appName = 1;</code>
   */
  public String getAppName() {
    return appName_;
  }
  /**
   * <code>optional string appName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAppNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(appName_);
  }
  /**
   * <code>optional string appName = 1;</code>
   */
  private void setAppName(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    appName_ = value;
  }
  /**
   * <code>optional string appName = 1;</code>
   */
  private void clearAppName() {
    
    appName_ = getDefaultInstance().getAppName();
  }
  /**
   * <code>optional string appName = 1;</code>
   */
  private void setAppNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    appName_ = value.toStringUtf8();
  }

  public static final int LEVEL_FIELD_NUMBER = 2;
  private int level_;
  /**
   * <code>optional .LogLevel level = 2;</code>
   */
  public int getLevelValue() {
    return level_;
  }
  /**
   * <code>optional .LogLevel level = 2;</code>
   */
  public tech.hry.logclient.grpc.LogLevel getLevel() {
    tech.hry.logclient.grpc.LogLevel result = tech.hry.logclient.grpc.LogLevel.forNumber(level_);
    return result == null ? tech.hry.logclient.grpc.LogLevel.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .LogLevel level = 2;</code>
   */
  private void setLevelValue(int value) {
      level_ = value;
  }
  /**
   * <code>optional .LogLevel level = 2;</code>
   */
  private void setLevel(tech.hry.logclient.grpc.LogLevel value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    level_ = value.getNumber();
  }
  /**
   * <code>optional .LogLevel level = 2;</code>
   */
  private void clearLevel() {
    
    level_ = 0;
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  private String title_;
  /**
   * <code>optional string title = 3;</code>
   */
  public String getTitle() {
    return title_;
  }
  /**
   * <code>optional string title = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <code>optional string title = 3;</code>
   */
  private void setTitle(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    title_ = value;
  }
  /**
   * <code>optional string title = 3;</code>
   */
  private void clearTitle() {
    
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <code>optional string title = 3;</code>
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    title_ = value.toStringUtf8();
  }

  public static final int MESSAGE_FIELD_NUMBER = 4;
  private String message_;
  /**
   * <code>optional string message = 4;</code>
   */
  public String getMessage() {
    return message_;
  }
  /**
   * <code>optional string message = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(message_);
  }
  /**
   * <code>optional string message = 4;</code>
   */
  private void setMessage(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    message_ = value;
  }
  /**
   * <code>optional string message = 4;</code>
   */
  private void clearMessage() {
    
    message_ = getDefaultInstance().getMessage();
  }
  /**
   * <code>optional string message = 4;</code>
   */
  private void setMessageBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    message_ = value.toStringUtf8();
  }

  public static final int TAGS_FIELD_NUMBER = 5;
  private static final class TagsDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        String, String> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<String, String>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapFieldLite<
      String, String> tags_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<String, String>
  internalGetTags() {
    return tags_;
  }
  private com.google.protobuf.MapFieldLite<String, String>
  internalGetMutableTags() {
    if (!tags_.isMutable()) {
      tags_ = tags_.mutableCopy();
    }
    return tags_;
  }

  public int getTagsCount() {
    return internalGetTags().size();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */

  public boolean containsTags(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetTags().containsKey(key);
  }
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @Deprecated
  public java.util.Map<String, String> getTags() {
    return getTagsMap();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */

  public java.util.Map<String, String> getTagsMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetTags());
  }
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */

  public String getTagsOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetTags();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */

  public String getTagsOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetTags();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */
  private java.util.Map<String, String>
  getMutableTagsMap() {
    return internalGetMutableTags();
  }

  public static final int TIME_FIELD_NUMBER = 6;
  private String time_;
  /**
   * <code>optional string time = 6;</code>
   */
  public String getTime() {
    return time_;
  }
  /**
   * <code>optional string time = 6;</code>
   */
  public com.google.protobuf.ByteString
      getTimeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(time_);
  }
  /**
   * <code>optional string time = 6;</code>
   */
  private void setTime(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    time_ = value;
  }
  /**
   * <code>optional string time = 6;</code>
   */
  private void clearTime() {
    
    time_ = getDefaultInstance().getTime();
  }
  /**
   * <code>optional string time = 6;</code>
   */
  private void setTimeBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    time_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!appName_.isEmpty()) {
      output.writeString(1, getAppName());
    }
    if (level_ != tech.hry.logclient.grpc.LogLevel.TRACE.getNumber()) {
      output.writeEnum(2, level_);
    }
    if (!title_.isEmpty()) {
      output.writeString(3, getTitle());
    }
    if (!message_.isEmpty()) {
      output.writeString(4, getMessage());
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetTags().entrySet()) {
      TagsDefaultEntryHolder.defaultEntry.serializeTo(
          output, 5, entry.getKey(), entry.getValue());
    }
    if (!time_.isEmpty()) {
      output.writeString(6, getTime());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!appName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getAppName());
    }
    if (level_ != tech.hry.logclient.grpc.LogLevel.TRACE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, level_);
    }
    if (!title_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getTitle());
    }
    if (!message_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getMessage());
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetTags().entrySet()) {
      size += TagsDefaultEntryHolder.defaultEntry.computeMessageSize(
        5, entry.getKey(), entry.getValue());
    }
    if (!time_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(6, getTime());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static tech.hry.logclient.grpc.SaveLogRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.hry.logclient.grpc.SaveLogRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.hry.logclient.grpc.SaveLogRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.hry.logclient.grpc.SaveLogRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.hry.logclient.grpc.SaveLogRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.hry.logclient.grpc.SaveLogRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static tech.hry.logclient.grpc.SaveLogRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static tech.hry.logclient.grpc.SaveLogRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static tech.hry.logclient.grpc.SaveLogRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.hry.logclient.grpc.SaveLogRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.hry.logclient.grpc.SaveLogRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code SaveLogRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        tech.hry.logclient.grpc.SaveLogRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:SaveLogRequest)
      tech.hry.logclient.grpc.SaveLogRequestOrBuilder {
    // Construct using tech.hry.logclient.SaveLogRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string appName = 1;</code>
     */
    public String getAppName() {
      return instance.getAppName();
    }
    /**
     * <code>optional string appName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      return instance.getAppNameBytes();
    }
    /**
     * <code>optional string appName = 1;</code>
     */
    public Builder setAppName(
        String value) {
      copyOnWrite();
      instance.setAppName(value);
      return this;
    }
    /**
     * <code>optional string appName = 1;</code>
     */
    public Builder clearAppName() {
      copyOnWrite();
      instance.clearAppName();
      return this;
    }
    /**
     * <code>optional string appName = 1;</code>
     */
    public Builder setAppNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAppNameBytes(value);
      return this;
    }

    /**
     * <code>optional .LogLevel level = 2;</code>
     */
    public int getLevelValue() {
      return instance.getLevelValue();
    }
    /**
     * <code>optional .LogLevel level = 2;</code>
     */
    public Builder setLevelValue(int value) {
      copyOnWrite();
      instance.setLevelValue(value);
      return this;
    }
    /**
     * <code>optional .LogLevel level = 2;</code>
     */
    public tech.hry.logclient.grpc.LogLevel getLevel() {
      return instance.getLevel();
    }
    /**
     * <code>optional .LogLevel level = 2;</code>
     */
    public Builder setLevel(tech.hry.logclient.grpc.LogLevel value) {
      copyOnWrite();
      instance.setLevel(value);
      return this;
    }
    /**
     * <code>optional .LogLevel level = 2;</code>
     */
    public Builder clearLevel() {
      copyOnWrite();
      instance.clearLevel();
      return this;
    }

    /**
     * <code>optional string title = 3;</code>
     */
    public String getTitle() {
      return instance.getTitle();
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public Builder setTitle(
        String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>optional string message = 4;</code>
     */
    public String getMessage() {
      return instance.getMessage();
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return instance.getMessageBytes();
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public Builder setMessage(
        String value) {
      copyOnWrite();
      instance.setMessage(value);
      return this;
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public Builder clearMessage() {
      copyOnWrite();
      instance.clearMessage();
      return this;
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageBytes(value);
      return this;
    }


    public int getTagsCount() {
      return instance.getTagsMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */

    public boolean containsTags(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return instance.getTagsMap().containsKey(key);
    }

    public Builder clearTags() {
      copyOnWrite();
      instance.getMutableTagsMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */

    public Builder removeTags(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      copyOnWrite();
      instance.getMutableTagsMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getTags() {
      return getTagsMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */
    public java.util.Map<String, String> getTagsMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getTagsMap());
    }
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */

    public String getTagsOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          instance.getTagsMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */

    public String getTagsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          instance.getTagsMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */
    public Builder putTags(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      copyOnWrite();
      instance.getMutableTagsMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */
    public Builder putAllTags(
        java.util.Map<String, String> values) {
      copyOnWrite();
      instance.getMutableTagsMap().putAll(values);
      return this;
    }

    /**
     * <code>optional string time = 6;</code>
     */
    public String getTime() {
      return instance.getTime();
    }
    /**
     * <code>optional string time = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      return instance.getTimeBytes();
    }
    /**
     * <code>optional string time = 6;</code>
     */
    public Builder setTime(
        String value) {
      copyOnWrite();
      instance.setTime(value);
      return this;
    }
    /**
     * <code>optional string time = 6;</code>
     */
    public Builder clearTime() {
      copyOnWrite();
      instance.clearTime();
      return this;
    }
    /**
     * <code>optional string time = 6;</code>
     */
    public Builder setTimeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTimeBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SaveLogRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new tech.hry.logclient.grpc.SaveLogRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        tags_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        tech.hry.logclient.grpc.SaveLogRequest other = (tech.hry.logclient.grpc.SaveLogRequest) arg1;
        appName_ = visitor.visitString(!appName_.isEmpty(), appName_,
            !other.appName_.isEmpty(), other.appName_);
        level_ = visitor.visitInt(level_ != 0, level_,    other.level_ != 0, other.level_);
        title_ = visitor.visitString(!title_.isEmpty(), title_,
            !other.title_.isEmpty(), other.title_);
        message_ = visitor.visitString(!message_.isEmpty(), message_,
            !other.message_.isEmpty(), other.message_);
        tags_ = visitor.visitMap(
            tags_, other.internalGetTags());
        time_ = visitor.visitString(!time_.isEmpty(), time_,
            !other.time_.isEmpty(), other.time_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                appName_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                level_ = rawValue;
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                title_ = s;
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                message_ = s;
                break;
              }
              case 42: {
                if (!tags_.isMutable()) {
                  tags_ = tags_.mutableCopy();
                }
                TagsDefaultEntryHolder.defaultEntry.parseInto(tags_, input, extensionRegistry);  break;
              }
              case 50: {
                String s = input.readStringRequireUtf8();

                time_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (tech.hry.logclient.grpc.SaveLogRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:SaveLogRequest)
  private static final tech.hry.logclient.grpc.SaveLogRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SaveLogRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static tech.hry.logclient.grpc.SaveLogRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SaveLogRequest> PARSER;

  public static com.google.protobuf.Parser<SaveLogRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

