// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_service.proto

package tech.hry.logclient.grpc;

public interface SaveLogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveLogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string appName = 1;</code>
   * @return The appName.
   */
  java.lang.String getAppName();
  /**
   * <code>string appName = 1;</code>
   * @return The bytes for appName.
   */
  com.google.protobuf.ByteString
      getAppNameBytes();

  /**
   * <code>.LogLevel level = 2;</code>
   * @return The enum numeric value on the wire for level.
   */
  int getLevelValue();
  /**
   * <code>.LogLevel level = 2;</code>
   * @return The level.
   */
  tech.hry.logclient.grpc.LogLevel getLevel();

  /**
   * <code>string title = 3;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string message = 4;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */

  java.lang.String getTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 5;</code>
   */

  java.lang.String getTagsOrThrow(
      java.lang.String key);

  /**
   * <code>string time = 6;</code>
   * @return The time.
   */
  java.lang.String getTime();
  /**
   * <code>string time = 6;</code>
   * @return The bytes for time.
   */
  com.google.protobuf.ByteString
      getTimeBytes();
}
